#!/bin/bash

if [ "x`git config user.name`" == "xSET_ME_LOCALLY" ]; then
  echo "fatal: user.name is not set locally."
  echo "please: git config user.name \$yourname"
  exit 1
fi

if [ "x`git config user.email`" == "xSET_ME_LOCALLY" ]; then
  echo "fatal: user.email is not set locally."
  echo "please: git config user.email \$yourname"
  exit 1
fi

