#!/bin/bash

# helpers

e_newline() {
  printf "\n"
}

e_header() {
  printf " \033[37;1m%s\033[m\n" "$*"
}

e_error() {
  printf " \033[31m%s\033[m\n" "✖ $*" 1>&2
}

e_done() {
  printf " \033[37;1m%s\033[m...\033[32mOK\033[m\n" "✔ $*"
}

e_arrow() {
  printf " \033[37;1m%s\033[m\n" "➜ $*"
}

is_exists() {
  which "$1" >/dev/null 2>&1
  return $?
}

contains() {
  string="$1"
  substring="$2"
  # pattern matching
  # if string is '/bin/bash' and substring is 'bash',
  # ${string#*$substring} is ''(pattern matching and remove by substring)
  if [ "${string#*$substring}" != "$string" ]; then
    return 0
  else
    return 1
  fi
}

ink() {
  if [ "$#" -eq 0 -o "$#" -gt 2 ]; then
    echo "Usage: ink <color> <text>"
    echo "Colors:"
    echo "  black, white, red, green, yellow, blue, purple, cyan, gray"
    return 1
  fi

  local open="\033["
  local close="${open}0m"
  local black="0;30m"
  local red="1;31m"
  local green="1;32m"
  local yellow="1;33m"
  local blue="1;34m"
  local purple="1;35m"
  local cyan="1;36m"
  local gray="0;37m"
  local white="$close"

  local text="$1"
  local color="$close"

  if [ "$#" -eq 2 ]; then
    text="$2"
    case "$1" in
      black | red | green | yellow | blue | purple | cyan | gray | white)
      eval color="\$$1"
      ;;
    esac
  fi

  printf "${open}${color}${text}${close}"
}

logging() {
  if [ "$#" -eq 0 -o "$#" -gt 2 ]; then
    echo "Usage: ink <fmt> <msg>"
    echo "Formatting Options:"
    echo "  TITLE, ERROR, WARN, INFO, SUCCESS"
    return 1
  fi

  local color=
  local text="$2"

  case "$1" in
    TITLE)
      color=yellow
      ;;
    ERROR | WARN)
      color=red
      ;;
    INFO)
      color=blue
      ;;
    SUCCESS)
      color=green
      ;;
    *)
      text="$1"
  esac

  timestamp() {
    ink gray "["
    ink purple "$(date +%H:%M:%S)"
    ink gray "] "
  }

  timestamp; ink "$color" "$text"; echo
}

log_pass() {
  logging SUCCESS "$1"
}

log_info() {
  logging INFO "$1"
}

log_warn() {
  logging WARN "$1"
}

log_fail() {
  logging ERROR "$1" 1>&2
}

lower() {
  # standard input
  if [ $# -eq 0 ]; then
    cat <&0
  # specify parameter
  elif [ $# -eq 1 ]; then
    # file
    if [ -f "$1" -a -r "$1" ]; then
      cat "$1"
    # string
    else
      echo "$1"
    fi
  else
    return 1
  fi | tr "[:upper:]" "[:lower:]"
}

ostype() {
  uname | lower
}

detect_os() {
  export PLATFORM
  case "$(ostype)" in
    *'linux'*) PLATFORM="linux" ;;
    *'darwin'*) PLATFORM="osx" ;;
    *) PLATFORM="unknown" ;;
  esac
}

# functions

download_dotfiles() {
  if [ -d "$DOTPATH" ]; then
    log_warn "$DOTPATH: already exists"
    return 1
  fi

  e_newline
  e_header "Downloading dotfiles..."

  if is_exists "git"; then
    git clone --recursive "$DOTFILES_GITHUB" "$DOTPATH"
  fi
  e_newline && e_done "Download"
}

deploy_dotfiles() {
  e_newline
  e_header "Deploying dotfiles..."
  if [ ! -d $DOTPATH ]; then
    log_fail "$DOTPATH: not found"
    exit 1
  fi

  cd "$DOTPATH"

  if [ -z "$DOTFILES" ]; then
    log_fail "DOTFILES is not found"
    exit 1
  fi

  # TODO: too many nest if directory
  for f in ${DOTFILES[@]}
  do
    ln -sfv $DOTPATH/$f $HOME/$f
  done

  export DOWNLOADED=1

  e_newline && e_done "Deploy"
}

initialize_dotfiles() {
  e_newline
  e_header "Initializing dotfiles..."
  detect_os
  bash $DOTPATH/etc/init/init.sh
}

install_dotfiles() {
  download_dotfiles
  deploy_dotfiles
  initialize_dotfiles
}

# executions

if [ ${DOWNLOADED:-0} = 1 ]; then
  return
fi

if [ -z "${DOTPATH:-}" ]; then
  DOTPATH=~/.dotfiles; export DOTPATH
fi
DOTFILES_GITHUB="https://github.com/takasing/avalanche.git"; export DOTFILES_GITHUB
DOTFILES=(\
  .git_template \
  .path \
  .peco \
  .tigrc \
  .tmux.conf \
  .vim.local \
  .vimrc
)

# echo AVALANCHE logo

install_dotfiles
# TODO: do not work helpers here...
#e_newline
#e_arrow "Restarting shell($SHELL)..."
$SHELL -l

