#!/bin/bash

unlink ~/.git_template
unlink ~/.path
unlink ~/.peco
unlink ~/.tigrc
unlink ~/.tmux.conf
unlink ~/.vim.local
unlink ~/.vimrc

if [ -z "${DOTPATH}" ]; then
  DOTPATH=~/.dotfiles
fi

rm -fr $DOTPATH

curl -sL https://raw.githubusercontent.com/t104fk/avalanche/master/etc/install | sh

