tap 'phinze/homebrew-cask' || true
tap 'caskroom/versions' || true
tap 'homebrew/versions' || true

install git || true
install tmux || true
install mysql55 && link mysql55 --force || true
install reattach-to-user-namespace || true
install csshx || true
install nkf || true

cleanup

install brew-cask || true

cask install java6 || true
cask install java7 || true

cask cleanup

